# Generated by Django 4.2 on 2023-05-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='katgori',
            new_name='kategori',
        ),
    ]
